blog/urls.py
from django.urls import path
from django.conf.urls import url
from blog import views

app_name = "blog"
urlpatterns = [
    url(r"^type/(?P<blog_type_pk>[0-9]+)$", views.blogs_with_type, name="blogs_with_type"),
    path(r"<int:blog_pk>", views.blog_detail, name="blog_detail"),
    url(r"blog_list/", views.blog_list, name="blog_list"),
    path(r"date/<int:year>/<int:month>/<int:day>", views.blogs_with_date, name="blogs_with_date"),
    path("", views.home, name="home"),

]

comment/urls.py
from django.urls import path
from comment import views

app_name = "comment"
urlpatterns = [
    path("blog_login", views.blog_login, name="blog_login"),    # 评论框，登陆页面
    path("update_comment", views.update_comment, name="update_comment"),    # 评论提交处理
    path("register", views.register, name="register"),  # 注册页面
    path("login_for_model", views.login_for_model, name="login_for_model"),   # 注册登陆框提交处理
]

likes/urls.py
from django.urls import path
from likes import views

app_name = "likes"
urlpatterns = [
	path("like_change", views.like_change, name="like_change"),


	
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path("comment/", include("comment.urls", namespace="comment")),
    path("likes/", include("likes.urls", namespace="likes")),
    path("blog_logout", views.blog_logout, name="blog_logout"),     # 用户退出
    path("user/", include("user.urls", namespace="user")),
    path("user_info", views.user_info, name="user_info"),
    path("", include("blog.urls", namespace="blog")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import ReadNumExpandMethod, ReadDetail
from django.contrib.contenttypes.fields import GenericRelation

class BlogType(models.Model):
    type_name = models.CharField(max_length=15)     # 博客类型

    def __str__(self):
        return self.type_name


class Blog(models.Model, ReadNumExpandMethod):
    title = models.CharField(max_length=50)     # 博客名字
    blog_type = models.ForeignKey(BlogType, on_delete=models.DO_NOTHING, related_name="blog")   # 关联类型
    content = RichTextUploadingField()    # 博客内容
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)   # 博客作者
    read_details = GenericRelation(ReadDetail)
    created_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    last_updated_time = models.DateTimeField(auto_now=True)     # 最后修改时间

    def get_url(self):
        return reverse("blog:blog_detail", kwargs={"blog_pk": self.pk})

    def get_email(self):
        return self.author.email

    def __str__(self):
        return "<Blog: %s>" % self.title
    class Meta:
        ordering = ["-created_time"]


# class ReadNum(models.Model):
#     read_num = models.IntegerField(default=0)  # 阅读数量统计
#     blog = models.OneToOneField(Blog, on_delete=models.DO_NOTHING)  # 一对一，一条博客只对应一条阅读量信息

blog/views.py
from django.shortcuts import render, get_object_or_404,get_list_or_404
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Count
from django.contrib.auth import authenticate
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from read_statistics.utils import get_seven_days_read_data
from blog.models import Blog, BlogType
from read_statistics.utils import read_statistics_once_read, get_today_hot_data, get_yesterday_hot_data,\
                                  get_7_days_hot_blogs,get_30_days_hot_blogs
from mysite.forms import LoginForm


def home(request):   # 首页
    blog_content_type = ContentType.objects.get_for_model(Blog)
    dates, read_nums = get_seven_days_read_data(blog_content_type)

    # 设置数据库缓存(获取7天热门博客数据缓存)
    hot_blogs_7_days = cache.get("hot_blogs_7_days", )
    # if hot_blogs_7_days is None:
    #     hot_blogs_7_days = get_7_days_hot_blogs()
    #     cache.set("hot_blogs_7_days", hot_blogs_7_days, 5)
    #     print("计算")
    # else:
    #     print("使用")

    cache.get_or_set("hot_blogs_7_days", hot_blogs_7_days, 5)

    context = {}
    context["read_nums"] = read_nums
    context["dates"] = dates
    context["today_hot_data"] = get_today_hot_data(blog_content_type)
    context["yesterday_hot_data"] = get_yesterday_hot_data(blog_content_type)
    context["hot_blogs_7_days"] = get_7_days_hot_blogs()
    context["hot_blogs_30_days"] = get_30_days_hot_blogs()
    return render(request, "home.html", context)

def get_blog_list_common_data(request, blog_all_list):   # 所有函数共用的函数方法
    paginator = Paginator(blog_all_list, settings.BLOG_NUMBER)  # 导入分页器进行分页,每3篇分为一页
    page_num = request.GET.get("page", "1")  # 获取用户request的页码
    page_of_blogs = paginator.get_page(page_num)  # 获取页面并且返回每页博客的数量

    # 博客分页优化(需求：只显示当前页码的前两页和后两页，以及最前最后页码)
    currentr_page_num = page_of_blogs.number  # 获取当前页码
    # 获取当前页码的前后两个的页码
    page_range = list(range(max(currentr_page_num - 2, 1), currentr_page_num)) + \
                 list(range(currentr_page_num, min(currentr_page_num + 2, paginator.num_pages) + 1))
    # 加上省略页码标记
    if page_range[0] - 1 >= 2:
        page_range.insert(0, "...")
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append("...")
    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    # # 获取博客分类中每个分类的对应博客数量
    # 第一种方法
    # blog_types = BlogType.objects.all()   # 1、获取所有的类型的查询集
    # blog_types_list = []
    # for blog_type in blog_types:    # 2、遍历该类型的所有博客的查询集
    #     # 3、筛选获取该查询集的个数，并且给该返回值设置一个方法
    #     blog_type.blog_count = Blog.objects.filter(blog_type=blog_type).count()
    #     blog_types_list.append(blog_type)   # 4、将返回值添加到一个列表中

    # 按照日期给博客进行归类
    blog_dates = Blog.objects.dates("created_time", "day", order="DESC")     # 1、获取创建时间的字段
    blog_dates_dict = {}    # 2、创建一个空的字典来进行传递参数
    for blog_date in blog_dates:       # 3、遍历获取每一条的统计日期
        blog_count = Blog.objects.filter(created_time__year=blog_date.year,     # 4、筛选出对应的博客数量
                                         created_time__month=blog_date.month,
                                         created_time__day=blog_date.day).count()
        # 5、将对应的博客数量和对应的日期利用字典的键值对关系，进行对应。日期对应数量，传递给模板
        blog_dates_dict[blog_date] = blog_count
    context = {}
    context["page_range"] = page_range
    context["blogs"] = page_of_blogs.object_list
    context["page_of_blogs"] = page_of_blogs  # 将返回每页的博客数量赋值给context
    # context["blog_types"] = blog_types_list       # 5、将这个列表返回传递给模板文件
    # 第二种方法统计对应分类的博客数量
    context["blog_types"] = BlogType.objects.annotate(blog_count=Count("blog"))

    context["blog_dates"] = blog_dates_dict   # 6、将日期博客归纳传递给模板
    return context

def blog_list(request):     # 博客列表页面
    blog_all_list = Blog.objects.all()      # 获取博客列表全部数据
    context = get_blog_list_common_data(request, blog_all_list)
    return render(request, 'blog/blog_list.html', context)


def blog_detail(request, blog_pk):  # 博客详情
    blog = get_object_or_404(Blog, pk=blog_pk)      # 取出对应的blog_pk中的Blog查询集
    read_cookie_key = read_statistics_once_read(request, blog)

    context = {}
    context["previous_blog"] = Blog.objects.filter(created_time__gt=blog.created_time).last()
    context["next_blog"] = Blog.objects.filter(created_time__lt=blog.created_time).first()
    context["blog"] = blog
    context["login_form"] = LoginForm()
    response = render(request, "blog/blog_detail.html", context)
    response.set_cookie(read_cookie_key, "true")
    return response

def blogs_with_type(request, blog_type_pk):  # 博客分类
    blog_type = get_list_or_404(BlogType, pk=blog_type_pk)
    blog_all_list = Blog.objects.filter(blog_type=blog_type_pk)  # 获取博客列表全部数据
    context = get_blog_list_common_data(request, blog_all_list)
    context["blog_type"] = blog_type
    return render(request, "blog/blgos_with_type.html", context)


def blogs_with_date(request, year, month, day):
    # 按照时间筛选出信息
    blog_all_list = Blog.objects.filter(created_time__year=year, created_time__month=month, created_time__day=day)  # 获取指定的年月分的博客数据
    context = get_blog_list_common_data(request, blog_all_list)
    context["blogs_with_date"] = "%s年%s月%s日" % (year, month, day)
    return render(request, 'blog/blogs_with_date.html', context)

templates/blog/blgos_with_type.html
{% extends "blog/blog_list.html" %}
{#页面标题#}
{% block title %}
     {% for i in blog_type %}
        我的博客网站--{{ i }}
    {% endfor %}
{% endblock %}

{% block blog_list_title %}
    {% for i in blog_type %}
        <span>{{ i }}</span>
    {% endfor %}
    <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock %}

templates/blog/blog_detail.html
{% extends "base.html" %}

{% load static %}
{% load comment_tags %}
{% load likes_tags %}

{% block header_extends %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js'%}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js'%}"></script>
{% endblock %}

{#页面标题#}
{% block title %}{{ blog.title }}{% endblock %}
{#页面导航栏#}
{% block nav_blog_active %}active{% endblock %}
{#页面内容#}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ blog.title }}</h3>
                <ul class="blog_info_con">
                    <li>作者：{{ blog.author }}</li>
                    <li>分类:<a href="{% url 'blog:blogs_with_type' blog.blog_type.id %}">{{ blog.blog_type }}</a></li>
                    <li>发表时间： {{ blog.created_time | date:"Y-m-d H:m:s"}}</li>
                    <li>阅读量({{ blog.get_read_num }})</li>
                    <li>评论({% get_comment_count blog %})</li>
                </ul>
                <div class="blog_content">{{ blog.content | safe}}</div>
                <div class="like" onclick="likeChange(this, '{% get_content_type blog %}', {{ blog.pk }})">
                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status blog %}"></span>
                    <span class="liked-num">{% get_like_count blog %}</span>
                    <span>喜欢</span>
                </div>
                <div class="blog_more">
                    <p>上一篇:
                        {% if previous_blog %}
                            <a href="{% url 'blog:blog_detail' previous_blog.id %}">{{ previous_blog.title }}</a>
                        {% else %}
                            木有了
                        {% endif %}
                    </p>
                    <p>下一篇:
                        {% if next_blog %}
                            <a href="{% url 'blog:blog_detail' next_blog.id %}" >{{ next_blog.title }}</a>
                        {% else %}
                            木有了
                        {% endif %}
                    </p> 
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="comment-area">
                    <h3 class="comment-area-title">提交评论</h3>
                        {% if user.is_authenticated %}
                            <form id="comment_form" action="{% url 'comment:update_comment' %}" method="post" style="overflow: hidden">
                                {% csrf_token %}
                                <label>{{ user.get_nickname_or_username}}，欢迎评论~~~</label>
                                <div id="reply_content_container" style="display: none;">
                                    <p id=reply_title>回复：</p>
                                    <div id="reply_content"></div>
                                </div>
                                {% get_commnet_form blog as comment_form %}
                                {% for filed in comment_form %}
                                    {{ filed }}
                                {% endfor %}
                                <span id="comment_error" class="text-danger pull-left"></span>
                                <input type="submit" value="评论" class="btn btn-primary pull-right">
                            </form>
                    {% else %}
                        您尚未登录,登陆之后方可评论~~~
                            <a class="btn btn-primary" href="{% url 'comment:blog_login' %}?from={{ request.get_full_path }}">登录</a>
                            <span>or</span>
                            <a class="btn btn-danger" href="{% url 'comment:register' %}?from={{ request.get_full_path }}">注册</a>
                    {% endif %}
                </div>
                <div class="comment-area">
                    <h3 class="comment-area-title">评论列表</h3>
                    <div id="comment_list">
                        {% get_comment_list blog as comments %}
                        {% for comment in comments %}
                            <div id="root_{{ comment.pk  }}" class="comment">
                                <span>{{ comment.user.get_nickname_or_username }}</span>
                                <span>({{ comment.comment_time| date:"Y-m-d H:m:s" }}):</span>
                                <div id="comment_{{ comment.pk }}">
                                    {{ comment.text|safe }}
                                </div>
                                <div class="like" onclick="likeChange(this, '{% get_content_type comment %}', {{ comment.pk }})">
                                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status comment %}"></span>
                                    <span class="liked-num">{% get_like_count comment %}</span>
                                </div>
                                <a href="javascript:reply({{ comment.pk }});">回复</a>
                            </div>


                            {% for reply in comment.root_comment.all  %}   <!--取出顶级评论下的所有回复-->
                                <div class="reply">
                                    <span>{{ reply.user.get_nickname_or_username }}</span>
                                    <span>({{ reply.comment_time| date:"Y-m-d H:m:s" }})</span>
                                    <span>回复</span>
                                    <span>{{ reply.reply_to.get_nickname_or_username }}:</span>
                                    <div id="comment_{{ reply.pk }}">
                                        {{ reply.text|safe }}
                                    </div>
                                     <div class="like" onclick="likeChange(this, '{% get_content_type reply %}', {{ reply.pk }})">
                                         <span class="glyphicon glyphicon-thumbs-up {% get_like_status reply %}"></span>
                                         <span class="liked-num">{% get_like_count reply %}</span>
                                     </div>
                                    <a href="javascript:reply({{ reply.pk }});">回复</a>
                                </div>
                            {% endfor %}
                        {% empty %}
                            <div id="comment_list_empty"> 暂无评论</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="login_model" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <form id="login_medal_form" action="" method="POST">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">登陆</h4>
                        </div>

                        <div class="modal-body">
                                {% csrf_token %}
                                {% for field in login_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                {% endfor %}
                                <span id="login_medal_tip" class="text-danger"></span>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">登陆</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        String.prototype.format = function(){
            var str = this;
            for(var i = 0; i < arguments.length; i++){
                var str = str.replace(new RegExp('\\{'+ i +'\\}', 'g'), arguments[i])
            };
            return str;
        };
        $("#comment_form").submit(function () {
            //判断是否为空
            $("#comment_error").text("");
            if (CKEDITOR.instances["id_text"].document.getBody().getText().trim() == ""){
                $("#comment_error").text("评论内容不能为空");
                return false;
            }
            //更新数据到textarea
            CKEDITOR.instances["id_text"].updateElement();
            // 异步提交
            $.ajax({
                url: "{% url 'comment:update_comment' %}",
                type: "POST",
                data: $(this).serialize(),
                cache: false,
                success: function (data) {
                    console.log(data);
                    if (data["status"] == "SUCCESS"){
                        //插入数据
                        if($("#reply_comment_id").val() == "0"){

                            //插入评论
                            var comment_html = '<div id="root_' + data['pk']+ '" class="comment"><span>' + data['username'] +'</span><span>('+ data['comment_time'] +'):</span><div id="comment_' + data['pk']+ '">'+ data['text'] +' </div> <a href="javascript:reply('+ data['pk']+');">回复</a></div>';
                            $("#comment_list").prepend(comment_html);
                        }else{

                            //插入回复
                            var reply_html = '<div class="reply"><span>' + data['username'] +'</span><span>('+ data['comment_time'] +')</span><span> 回复 </span><span>'+ data['reply_to'] +':</span><div id="comment_'+ data['pk'] +'">'+ data['text'] +'</div><a href="javascript:reply('+ data['pk'] +');">回复</a></div>'
                            $("#root_" + data['root_pk']).append(reply_html);
                        }
                        //清空编辑框的内容
                        CKEDITOR.instances["id_text"].setData("");
                        $("#reply_content_container").hide();
                        $("#reply_comment_id").val('0');
                        $("#comment_list_empty").remove();
                        $("#comment_error").text("评论成功");
                    }else{
                        //显示错误信息
                        $("#comment_error").text(data["message"]);
                    }
                },
                error: function (xhr) {
                    console.log(xhr);
                }
            });
            return false;
        });
        function reply(reply_comment_id) {
            //设置值
            $("#reply_comment_id").val(reply_comment_id);
            var html = $("#comment_" + reply_comment_id).html();
            $("#reply_content").html(html);
            $("#reply_content_container").show();
            $("html").animate({scrollTop:$("#comment_form").offset().top - 60}, 300, function () {
                CKEDITOR.instances["id_text"].focus();
            });
        }
        function likeChange(obj, content_type, object_id){
            var is_like = obj.getElementsByClassName('active').length == 0
            $.ajax({
                url: "{% url 'likes:like_change' %}",
                type: 'GET',
                data: {
                    content_type: content_type,
                    object_id: object_id,
                    is_like: is_like,
                },
                cache: false,
                success: function(data){
                    console.log(data);
                    if(data["status"]=='SUCCESS'){
                        //更新点赞状态
                        var element = $(obj.getElementsByClassName('glyphicon'));
                        if (is_like){
                            element.addClass('active');
                        }else{
                            element.removeClass('active');
                        }
                        //更新点赞数量
                        var liked_num = $(obj.getElementsByClassName('liked-num'));
                        liked_num.text(data["liked_num"]);
                    }else {
                        if(data['code']==400){
                            $('#login_model').modal('show');
                        }else {
                            alert(data['message']);
                        }

                    }
                },
                error: function(xhr){
                    console.log(xhr)
                }
            })
        }
        $("#login_medal_form").submit(function (event) {
            event.preventDefault();
            $.ajax({
                url: "{% url 'comment:login_for_model' %}",
                type: "POST",
                data: $(this).serialize(),
                cache: false,
                success: function (data) {
                    if(data['status']=='SUCCESS'){
                        window.location.reload();
                    }else {
                        $("#login_medal_tip").text('用户名或者密码不正确')
                    }
                }
            });
        })
    </script>
{% endblock %}

templates/blog/blog_list.html
{% extends "base.html" %}

{% load static %}
{% load comment_tags %}
{% load likes_tags %}

{% block header_extends %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
{% endblock %}

{#页面标题#}
{% block title %}我的网站{% endblock %}
{% block nav_blog_active %}active{% endblock %}

{#页面内容#}
{% block content %}
    <div class="container">
        <div class="row">

            {#博客列表内容#}
            <div class="col-sm-8 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% block blog_list_title %}
                            博客列表
                        {% endblock %}
                    </div>
                    <div class="panel-body">
                        {% for blog in blogs %}
                            <div class="blog">
                                <h3><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></h3>
                                <p class="blog_info">
                                    <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                                    <a href="{% url 'blog:blogs_with_type' blog.blog_type.id %}">
                                        {{ blog.blog_type }}
                                    </a>
                                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                    {{ blog.created_time | date:"Y-m-d" }}
                                    <span>阅读量({{ blog.get_read_num }})</span>&nbsp;&nbsp;
                                    <span>评论({% get_comment_count blog %})</span>&nbsp;&nbsp;
                                    <span>点赞({% get_like_count blog %})</span>
                                </p>
                                <p>{{ blog.content | truncatechars:10 }}</p>
                            </div>
                        {% empty %}
                              <div class="blog">
                                <p>-----暂无博客，敬请期待！--------</p>
                              </div>
                        {% endfor %}
                        {#博客分页#}
                              <ul class="pagination">
                              {# 上一页 #}
                                <li>
                                    {% if page_of_blogs.has_previous %}
                                  <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                  </a>
                                    {% else %}
                                        <span aria-hidden="true">&laquo;</span>
                                    {% endif %}
                                </li>
                                  {#全部页码#}
                                  {% for page_num in page_range%}
                                      {% if page_num == page_of_blogs.number%}
                                          <li class="active"><span>{{ page_num }}</span></li>
                                      {% else %}
                                          {% if page_num == "..." %}
                                              <li><span>{{ page_num }}</span></li>
                                          {% else %}
                                              <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                          {% endif %}
                                      {% endif %}
                                  {% endfor %}
                                  {# 下一页 #}
                                <li>
                                    {% if page_of_blogs.has_next %}
                                  <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                  </a>
                                    {% else %}
                                        <span aria-hidden="true">&raquo;</span>
                                    {% endif %}
                                </li>
                              </ul>
                        <p>
                            共有{{ page_of_blogs.paginator.count}}篇博客
                            当前为{{ page_of_blogs.number }}页，
                            共有{{ page_of_blogs.paginator.num_pages}}页
                        </p>
                      </div>
                </div>
            </div>

            {#博客分类区域#}
            <div class="col-sm-4 col-lg-2">
                <div class="panel panel-default">
                      <div class="panel-heading">博客分类</div>
                      <div class="panel-body">
                        <ul class="blog_type">
                            {% for blog in blog_types %}
                                <li>
                                    <a href="{% url 'blog:blogs_with_type' blog.id %}">
                                        {{ blog.type_name }}({{ blog.blog_count }})
                                    </a>
                                </li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                      </div>
                </div>
                {#按照日期归纳#}
                <div class="panel panel-default">
                      <div class="panel-heading">日期归纳</div>
                      <div class="panel-body">
                        <ul class="blog_type">
                            {% for blog_date, blog_count in blog_dates.items %}
                                <li>
                                   <a href="{% url 'blog:blogs_with_date' blog_date.year blog_date.month blog_date.day %}">
                                       {{ blog_date | date:"Y年m月d日" }}({{ blog_count }})
                                   </a>
                                </li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                      </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/blogs_with_date.html
{% extends "blog/blog_list.html" %}
{#页面标题#}
{% block title %}
    日期归纳
{% endblock %}

{% block blog_list_title %}
    {{ blogs_with_date }}的博客&nbsp
    <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock %}