blog/urls.py
from django.urls import path
from django.conf.urls import url
from blog import views

app_name = "blog"
urlpatterns = [
    url(r"^type/(?P<blog_type_pk>[0-9]+)$", views.blogs_with_type, name="blogs_with_type"),
    path(r"<int:blog_pk>", views.blog_detail, name="blog_detail"),
    url(r"blog_list/", views.blog_list, name="blog_list"),
    path(r"date/<int:year>/<int:month>/<int:day>", views.blogs_with_date, name="blogs_with_date"),
    path("", views.home, name="home"),

]

comment/urls.py
from django.urls import path
from comment import views

app_name = "comment"
urlpatterns = [
    path("blog_login", views.blog_login, name="blog_login"),    # 评论框，登陆页面
    path("update_comment", views.update_comment, name="update_comment"),    # 评论提交处理
    path("register", views.register, name="register"),  # 注册页面
    path("login_for_model", views.login_for_model, name="login_for_model"),   # 注册登陆框提交处理
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor", include("ckeditor_uploader.urls")),
    path("comment/", include("comment.urls", namespace="comment")),
    path("likes/", include("likes.urls", namespace="likes")),
    path("blog_logout", views.blog_logout, name="blog_logout"),     # 用户退出
    path("user/", include("user.urls", namespace="user")),
    path("user_info", views.user_info, name="user_info"),
    path("", include("blog.urls", namespace="blog")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("change_nick_name", views.change_nick_name, name="change_nick_name"),
    path("bind_email", views.bind_email, name="bind_email"),
    path("send_verification_code", views.send_verification_code, name="send_verification_code"),
    path("change_password", views.change_password, name="change_password"),
    path("forgot_password", views.forgot_password, name="forgot_password"),
]

user/forms.py
from django import forms
from django.contrib.auth.models import User

class ChangeNickForm(forms.Form):
    nickname_new = forms.CharField(
        label="新的昵称",
        max_length=20,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入新的昵称"})
    )

    def __init__(self, *args, **kwargs):
        if "user" in kwargs:
            self.user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

    def clean(self):        # 评论对象验证
        # 判断用户是否登陆
        if self.user.is_authenticated:
            self.cleaned_data["user"] = self.user
        else:
            raise forms.ValidationError("用户尚未登录")
        return self.cleaned_data


    def clean_nikename_new(self):
        nickname_new = self.cleaned_data.get("nickname_new", "").strip()
        if nickname_new == "":
            raise forms.ValidationError("新的昵称不能为空")
        return nickname_new


class BinEmailForm(forms.Form):
    email = forms.EmailField(
        label="邮箱",
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入正确的邮箱'}
        )
    )

    verification_code = forms.CharField(
        label="验证码",
        required=False,  # 设置验证码为不必填写，因为先提交邮箱的时候，还不能填写验证码，如果必填会弹出错误信息
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': "点击'发送验证码'，发送到邮箱"}
        )
    )

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.request.user.is_authenticated:
            self.cleaned_data["user"] = self.request.user
        else:
            raise forms.ValidationError("用户尚未登录")

        # 判断用户是否已经绑定邮箱
        if self.request.user.email != "":
            raise forms.ValidationError("您已经绑定邮箱！")

        # 验证验证码是否正确
        code = self.request.session.get("bind_email_code", "")   # 取出缓存中生成的验证码
        verification_code = self.cleaned_data.get("verification_code", "")      # 取出用户输入的验证码

        if not(code == verification_code and code != ""):
            raise forms.ValidationError("验证码不正确！")

        return self.cleaned_data

    def clean_email(self):   # 验证邮箱是否已经存在在数据库，
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("该邮箱已经被绑定")
        return email

    def clean_verification_code(self):   # 验证  验证码是否为空
        verification_code = self.cleaned_data.get("verification_code", "").strip()
        if verification_code == "":
            raise forms.ValidationError("验证码不能为空")
        return verification_code

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    {% block header_extends %}{% endblock %}

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top"  role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    我的博客网站
                </a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" >
                    <li class="{% block nav_home_avtive %}{% endblock %}">
                        <a href="/">首页</a>
                    </li>
                    <li class="{% block nav_blog_active %}{% endblock %}">
                        <a href="{% url 'blog:blog_list'%}">博客</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url 'comment:blog_login' %}?from={{ request.get_full_path }}">登录</a>
                        </li>
                        <li>
                            <a href="{% url 'comment:register' %}?from={{ request.get_full_path }}">注册</a>
                        </li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                {{ user }} ({{ user.get_nickname_or_username}})
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user_info' %}">个人资料</a></li>
                                <li><a href="{% url 'user:change_password' %}">修改密码</a></li>
                                {% if user.is_staff or is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                {% endif %}
                                <li><a href="{% url 'blog_logout' %}?from={{ request.get_full_path }}">退出</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content%}{% endblock %}
    {% block script_extends %}{% endblock %}
</body>
</html>

templates/bind_email.html
{% extends "forms.html" %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
    <script>
    $("#send_code").click(function () {
        var email = $("#id_email").val();
        if (email == ""){
            $("#tip").text("*邮箱不能为空");
            return false;
        }

        // 发送验证码
        $.ajax({
            url: "{% url 'user:send_verification_code' %}",
            type: "GET",
            async : false,
            data: {
                "email": email,
                "send_for": "bing_email_code",
            },
            cache: false,
            success: function (data) {
                if(data["status"] == "ERROR"){
                    alert(data["status"]);
                }
            }
        });
        // 把按钮变灰色
        $(this).addClass("disabled");
        $(this).attr("disabled", true);
        var time = 30;
        $(this).text(time + "s");
        var interval = setInterval(() => {
            if(time <= 0){
                clearInterval(interval);
                $(this).removeClass("disabled");
                $(this).attr("disabled", false);
                $(this).text("发送验证码");
                return false;
        }
            time --;
            $(this).text(time + "s");
        }, 1000);
    });
    </script>
{% endblock %}

templates/error.html
{% extends "base.html" %}
{% load static %}

# 标题
{% block title%}
    我的网站|错误
{% endblock %}


{% block nav_home_avtive %}active{% endblock %}



{% block content%}
   {{ message }}<a href="{{ redirect_to }}">返回博客</a>
{% endblock %}

templates/forgot_password.html
{% extends "forms.html" %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
    <script>
    $("#send_code").click(function () {
        var email = $("#id_email").val();
        if (email == ""){
            $("#tip").text("*邮箱不能为空");
            return false;
        }

        // 发送验证码
        $.ajax({
            url: "{% url 'user:send_verification_code' %}",
            type: "GET",
            async : false,
            data: {
                "email": email,
                "send_for": "forgot_password_code",
            },
            cache: false,
            success: function (data) {
                if(data["status"] == "ERROR"){
                    alert(data["status"]);
                }
            }
        });
        // 把按钮变灰色
        $(this).addClass("disabled");
        $(this).attr("disabled", true);
        var time = 30;
        $(this).text(time + "s");
        var interval = setInterval(() => {
            if(time <= 0){
                clearInterval(interval);
                $(this).removeClass("disabled");
                $(this).attr("disabled", false);
                $(this).text("发送验证码");
                return false;
        }
            time --;
            $(this).text(time + "s");
        }, 1000);
    });
    </script>
{% endblock %}

templates/forms.html
{% extends "base.html" %}
{% load static %}

# 标题
{% block title%}
    {{ page_title }}
{% endblock %}

{% block nav_home_avtive %}active{% endblock %}

{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-xs-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="#" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="pull-left text-danger login_form_error">{{ form.non_field_errors.0 }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}{% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

# 标题
{% block title%}
    我的网站|首页
{% endblock %}

{% block header_extends %}
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_avtive %}active{% endblock %}
# 内容
{% block content%}
    <h3 class="home_content">记录学习的点点滴滴！可能对你有所帮助！</h3>
    <div id="container"></div>
    <div class="hot-data">
        <h3 class="today_hot_data">今天的热门博客</h3>
        <ul>
            {% for hot_data in today_hot_data %}
                <li>
                    <a href="{% url 'blog:blog_detail' hot_data.object_id %}">
                    {{ hot_data.content_object.title }}({{ hot_data.read_num }})
                    </a>
                </li>
            {% empty %}
                <li>今天暂无热门博客</li>
            {% endfor %}
        </ul>
    </div>

    <div class="hot-data">
            <h3>昨天的热门博客</h3>
            <ul>
                {% for hot_data in yesterday_hot_data %}
                    <li>
                        <a href="{% url 'blog:blog_detail' hot_data.object_id %}">
                        {{ hot_data.content_object.title }}({{ hot_data.read_num }})
                        </a>
                    </li>
                {% empty %}
                    <li>昨天暂无热门博客</li>
                {% endfor %}
            </ul>
    </div>

    <div class="hot-data">
        <h3>本周的热门博客</h3>
        <ul>
            {% for hot_data in hot_blogs_7_days %}
                <li>
                    <a href="{% url 'blog:blog_detail' hot_data.id %}">
                    {{ hot_data.title}}({{ hot_data.read_num_sum }})
                    </a>
                </li>
            {% empty %}
                <li>本周暂无热门博客</li>
            {% endfor %}
        </ul>
    </div>

    <div class="hot-data">
        <h3>本月的热门博客</h3>
        <ul>
            {% for hot_data in hot_blogs_30_days %}
                <li>
                    <a href="{% url 'blog:blog_detail' hot_data.id %}">
                    {{ hot_data.title}}({{ hot_data.read_num_sum }})
                    </a>
                </li>
            {% empty %}
                <li>本周暂无热门博客</li>
            {% endfor %}
        </ul>
    </div>

    <script>
        // 图表配置
        var options = {
            chart: {
                type: 'line'                          //指定图表的类型，默认是折线图（line）
            },
            title: {
                text: null               // 标题
            },
            xAxis: {
                categories: {{ dates | safe }},   // x 轴分类
                tickmarkPlacement: "on",
                title: {text: "前七日阅读量变化"},
            },
            yAxis: {
                title: {text: null},             // y 轴标题},
                labels:{enabled:false},
                gridLineDashStyle: "Dash",
            },
            series: [{                              // 数据列
                name: '阅读量',                        // 数据列名
                data: {{ read_nums }}                  // 数据
            },],
            plotOptions: {                  // 数据标签开启
                line: {
                    dataLabels: {
                        enabled: true,
                        formatter: function() {
                            return this.x + "   " + this.y;
                        },
                        // format: "{x}      {y}"
                    }
                }
            },
            legend:{enabled:false},     // 图例设置为不需要
            credits: {enabled:false},    // 版权信息设置为不需要
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}

# 标题
{% block title%}
    我的网站|登陆
{% endblock %}

{% block nav_home_avtive %}active{% endblock %}

{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-xs-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="#" method="POST">
                            {% csrf_token %}
                            {% for field in login_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger login_form_error">{{ login_form.non_field_errors.0 }}</span>
                            <a href="{% url 'user:forgot_password' %}" class="pull-left">忘记密码？</a>
                            <input type="submit" value="登陆" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load static %}

# 标题
{% block title%}
    我的网站|注册
{% endblock %}

{% block nav_home_avtive %}active{% endblock %}

{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
            {% if not user.is_authenticated %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">注册</h3>
                    </div>
                        <div class="panel-body">
                            <form action="#" method="POST">
                                {% csrf_token %}
                                {% for field in reg_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class=" text-danger login_form_error">{{ reg_form.non_field_errors.0 }}</span>
                                <div class="clearfix"></div>
                                <button id="send_code" class="btn btn-primary pull-left">发送验证码</button>
                                <input type="submit" value="注册" class="btn btn-primary pull-right">
                            </form>
                        </div>
                {% else %}
                       <h3>已经登录，跳转到首页... ...</h3>
                        <script>
                            setTimeout(function () {
                                window.location.href = "/";
                            }, 1500);
                        </script>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script_extends %}
    <script>
    $("#send_code").click(function () {
        var email = $("#id_email").val();
        if (email == ""){
            $("#tip").text("*邮箱不能为空");
            return false;
        }

        // 发送验证码
        $.ajax({
            url: "{% url 'user:send_verification_code' %}",
            type: "GET",
            async : false,
            data: {
                "email": email,
                "send_for": "register_code",
            },
            cache: false,
            success: function (data) {
                if(data["status"] == "ERROR"){
                    alert(data["status"]);
                }
            }
        });
        // 把按钮变灰色
        $(this).addClass("disabled");
        $(this).attr("disabled", true);
        var time = 30;
        $(this).text(time + "s");
        var interval = setInterval(() => {
            if(time <= 0){
                clearInterval(interval);
                $(this).removeClass("disabled");
                $(this).attr("disabled", false);
                $(this).text("发送验证码");
                return false;
        }
            time --;
            $(this).text(time + "s");
        }, 1000);
    });
    </script>
{% endblock %}

templates/user_info.html
{% extends "base.html" %}
{% load static %}

# 标题
{% block title%}
    我的网站|注册
{% endblock %}
{% block nav_home_avtive %}active{% endblock %}
{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                   <h2>{{ user.username }}</h2>
                    <ul style="line-height: 5em;">
                        <li>昵称：{{ user.get_nickname_or_username }}
                            <a href="{% url 'user:change_nick_name' %}?from={{ request.get_full_path }}">修改昵称</a>
                        </li>
                        <li>邮箱：
                            {% if user.email %}
                                {{ user.email }}
                            {% else %}
                                未绑定&nbsp;<a href="{% url 'user:bind_email' %}">绑定邮箱</a>
                            {% endif %}
                        </li>
                        <li>
                            上一次登录的时间：
                            {{ user.last_login }}
                        </li>
                        <li><a href="{% url 'user:change_password' %}">修改密码</a></li>
                    </ul>
                {% else %}
                    <span>未登录，跳转到首页... ...</span>
                    <script>
                        setTimeout(function () {
                            window.location.href = "/";
                        }, 1000);
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}